package com.lifesync.service.impl;

import com.lifesync.service.AIService;
import com.lifesync.dto.AIWorkoutRequestDTO;
import com.lifesync.entity.WorkoutPlan;
import com.lifesync.entity.User;
import com.lifesync.entity.Progress;
import com.lifesync.entity.Workout;
import com.lifesync.repository.UserRepository;
import com.lifesync.repository.ProgressRepository;
import com.lifesync.repository.WorkoutRepository;
import com.lifesync.utility.BackendException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.*;

@Service
@Transactional
public class AIServiceImpl implements AIService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ProgressRepository progressRepository;

    @Autowired
    private WorkoutRepository workoutRepository;

    // Exercise database for AI recommendations
    private final Map<String, List<String>> exerciseDatabase = Map.of(
        "chest", Arrays.asList("Push-ups", "Bench Press", "Dumbbell Flyes", "Incline Press", "Cable Crossovers"),
        "back", Arrays.asList("Pull-ups", "Deadlifts", "Bent-over Rows", "Lat Pulldowns", "Seated Rows"),
        "legs", Arrays.asList("Squats", "Lunges", "Leg Press", "Calf Raises", "Hamstring Curls"),
        "shoulders", Arrays.asList("Overhead Press", "Lateral Raises", "Front Raises", "Reverse Flyes", "Shrugs"),
        "arms", Arrays.asList("Bicep Curls", "Tricep Extensions", "Hammer Curls", "Dips", "Push-ups"),
        "core", Arrays.asList("Planks", "Crunches", "Russian Twists", "Leg Raises", "Mountain Climbers")
    );

    @Override
    public WorkoutPlan generatePersonalizedWorkoutPlan(AIWorkoutRequestDTO request) {
        User user = userRepository.findById(request.getUserId())
            .orElseThrow(() -> new BackendException("User not found"));

        // Create workout plan based on AI logic
        WorkoutPlan plan = new WorkoutPlan();
        plan.setName("AI Generated Plan - " + request.getObjective());
        plan.setDescription("Personalized workout plan generated by AI based on your profile and goals");
        plan.setDurationWeeks(request.getDurationWeeks() != null ? request.getDurationWeeks() : 8);
        plan.setDifficulty(request.getDifficulty());
        plan.setObjective(request.getObjective());
        plan.setEquipment(request.getEquipment() != null ? request.getEquipment() : "basic");
        plan.setUser(user);
        
        // Generate workout days based on request
        int daysPerWeek = request.getDaysPerWeek() != null ? request.getDaysPerWeek() : 3;
        plan.setDaysPerWeek(daysPerWeek);
        
        // Set completion tracking
        plan.setCompleted(false);
        plan.setCompletionPercentage(0);
        
        return plan; // In a real implementation, this would generate actual workout days
    }

    @Override
    @Transactional(readOnly = true)
    public List<String> generateWorkoutRecommendations(Long userId, String muscleGroup, String equipment) {
        List<String> baseExercises = exerciseDatabase.getOrDefault(muscleGroup.toLowerCase(), 
            Arrays.asList("General exercises for " + muscleGroup));

        // Filter based on equipment availability
        if (equipment != null && equipment.equals("none")) {
            return baseExercises.stream()
                .filter(exercise -> !exercise.contains("Press") && !exercise.contains("Machine"))
                .limit(5)
                .toList();
        } else if (equipment != null && equipment.equals("basic")) {
            return baseExercises.stream()
                .filter(exercise -> !exercise.contains("Cable") && !exercise.contains("Machine"))
                .limit(5)
                .toList();
        }
        
        return baseExercises.stream().limit(5).toList();
    }

    @Override
    @Transactional(readOnly = true)
    public Map<String, Object> analyzeUserProgress(Long userId) {
        List<Progress> progressHistory = progressRepository.findByUserIdOrderByDateDesc(userId);
        
        Map<String, Object> analysis = new HashMap<>();
        
        if (progressHistory.isEmpty()) {
            analysis.put("status", "no_data");
            analysis.put("message", "No progress data available for analysis");
            return analysis;
        }

        // Calculate progress trends
        Progress latest = progressHistory.get(0);
        Progress first = progressHistory.get(progressHistory.size() - 1);
        
        // Weight analysis
        if (latest.getWeight() != null && first.getWeight() != null) {
            double weightChange = latest.getWeight() - first.getWeight();
            analysis.put("weightChange", weightChange);
            analysis.put("weightTrend", weightChange > 0 ? "increasing" : "decreasing");
        }
        
        // Body fat analysis
        if (latest.getBodyFat() != null && first.getBodyFat() != null) {
            int bodyFatChange = latest.getBodyFat() - first.getBodyFat();
            analysis.put("bodyFatChange", bodyFatChange);
            analysis.put("bodyFatTrend", bodyFatChange > 0 ? "increasing" : "decreasing");
        }
        
        // Progress consistency
        long totalDays = progressHistory.size();
        analysis.put("totalProgressEntries", totalDays);
        analysis.put("progressConsistency", totalDays >= 10 ? "high" : totalDays >= 5 ? "medium" : "low");
        
        // Recommendations
        List<String> recommendations = new ArrayList<>();
        if (totalDays < 5) {
            recommendations.add("Try to track progress more consistently (at least weekly)");
        }
        if (latest.getWeight() != null && first.getWeight() != null) {
            double weightChange = latest.getWeight() - first.getWeight();
            if (Math.abs(weightChange) < 0.5) {
                recommendations.add("Consider adjusting your workout or nutrition plan for better results");
            }
        }
        analysis.put("recommendations", recommendations);
        
        return analysis;
    }

    @Override
    @Transactional(readOnly = true)
    public Map<String, Object> suggestGoals(Long userId) {
        User user = userRepository.findById(userId)
            .orElseThrow(() -> new BackendException("User not found"));
        
        List<Progress> progressHistory = progressRepository.findByUserIdOrderByDateDesc(userId);
        
        Map<String, Object> goals = new HashMap<>();
        
        // Current stats
        if (!progressHistory.isEmpty()) {
            Progress latest = progressHistory.get(0);
            goals.put("currentWeight", latest.getWeight());
            goals.put("currentBodyFat", latest.getBodyFat());
            goals.put("currentMuscleMass", latest.getMuscleMass());
        }
        
        // Goal suggestions based on current state
        List<Map<String, Object>> suggestedGoals = new ArrayList<>();
        
        // Weight loss goal
        if (!progressHistory.isEmpty() && progressHistory.get(0).getWeight() != null) {
            double currentWeight = progressHistory.get(0).getWeight();
            if (currentWeight > 70) {
                Map<String, Object> weightLossGoal = new HashMap<>();
                weightLossGoal.put("type", "weight_loss");
                weightLossGoal.put("target", currentWeight - 5.0);
                weightLossGoal.put("timeline", "8 weeks");
                weightLossGoal.put("difficulty", "medium");
                suggestedGoals.add(weightLossGoal);
            }
        }
        
        // Muscle gain goal
        if (!progressHistory.isEmpty() && progressHistory.get(0).getMuscleMass() != null) {
            double currentMuscleMass = progressHistory.get(0).getMuscleMass();
            Map<String, Object> muscleGainGoal = new HashMap<>();
            muscleGainGoal.put("type", "muscle_gain");
            muscleGainGoal.put("target", currentMuscleMass + 2.0);
            muscleGainGoal.put("timeline", "12 weeks");
            muscleGainGoal.put("difficulty", "high");
            suggestedGoals.add(muscleGainGoal);
        }
        
        // Consistency goal
        Map<String, Object> consistencyGoal = new HashMap<>();
        consistencyGoal.put("type", "consistency");
        consistencyGoal.put("target", "workout 4x per week");
        consistencyGoal.put("timeline", "4 weeks");
        consistencyGoal.put("difficulty", "medium");
        suggestedGoals.add(consistencyGoal);
        
        goals.put("suggestedGoals", suggestedGoals);
        
        return goals;
    }

    @Override
    @Transactional(readOnly = true)
    public Map<String, Object> getWorkoutAdjustments(Long userId, Long currentWorkoutPlanId) {
        Map<String, Object> adjustments = new HashMap<>();
        
        // Get user's recent progress
        List<Progress> recentProgress = progressRepository.getProgressSinceDate(userId, LocalDate.now().minusWeeks(2));
        
        if (recentProgress.isEmpty()) {
            adjustments.put("status", "no_recent_data");
            adjustments.put("message", "No recent progress data available for adjustments");
            return adjustments;
        }
        
        // Analyze recent trends
        List<String> suggestions = new ArrayList<>();
        
        Progress latest = recentProgress.get(0);
        Progress twoWeeksAgo = recentProgress.get(recentProgress.size() - 1);
        
        // Weight trend analysis
        if (latest.getWeight() != null && twoWeeksAgo.getWeight() != null) {
            double weightChange = latest.getWeight() - twoWeeksAgo.getWeight();
            if (weightChange > 1.0) {
                suggestions.add("Consider increasing cardio intensity for weight management");
            } else if (weightChange < -1.0) {
                suggestions.add("Ensure adequate protein intake to preserve muscle mass");
            }
        }
        
        // Plateau detection
        if (latest.getWeight() != null && twoWeeksAgo.getWeight() != null) {
            double weightChange = Math.abs(latest.getWeight() - twoWeeksAgo.getWeight());
            if (weightChange < 0.2) {
                suggestions.add("Consider varying your workout routine to break through plateau");
                suggestions.add("Try progressive overload - increase weights or reps");
            }
        }
        
        // General recommendations
        suggestions.add("Ensure proper rest and recovery between workouts");
        suggestions.add("Stay hydrated and maintain consistent nutrition");
        
        adjustments.put("suggestions", suggestions);
        adjustments.put("adjustmentType", "routine_optimization");
        
        return adjustments;
    }
}
